import { StyleSheet } from 'react-native';
import { Colors } from '../constants/theme';

export const moveModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 36,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 12,
  },
  modalTitle: { fontSize: 17, fontWeight: '700', color: Colors.text, marginBottom: 4 },
  modalSub:   { fontSize: 13, color: Colors.textSub, marginBottom: 16 },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.border,
    marginBottom: 10,
    backgroundColor: Colors.subtle,
  },
  modalOptionCurrent:    { borderColor: Colors.borderMid, backgroundColor: Colors.bg, opacity: 0.6 },
  modalDot:              { width: 12, height: 12, borderRadius: 99 },
  modalOptionTxt:        { fontSize: 15, fontWeight: '600', color: Colors.text, flex: 1 },
  modalOptionTxtCurrent: { color: Colors.textSub },
  modalCurrentBadge: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textSub,
    backgroundColor: Colors.bg,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: Colors.borderMid,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  modalCancel: {
    marginTop: 4,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: Colors.borderMid,
    backgroundColor: Colors.surface,
  },
  modalCancelTxt: { fontSize: 15, fontWeight: '600', color: Colors.textSub },
});
