import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../constants/theme';

export const screenStyles = StyleSheet.create({
  safe:        { flex: 1, backgroundColor: Colors.bg },
  content:     { flex: 1 },
  scroll:      { padding: 12, paddingBottom: 40 },
  centered:    { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  loadingText: { fontSize: 16, color: Colors.text, fontWeight: '600' },
  errorText:   { fontSize: 16, color: '#b91c1c', fontWeight: '700', marginBottom: 8 },
  errorSub:    { fontSize: 14, color: Colors.textSub, textAlign: 'center', lineHeight: 20 },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    backgroundColor: Colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: { fontSize: 17, fontWeight: '700', color: Colors.text },
  headerSub:   { fontSize: 12, color: Colors.textSub, marginTop: 1 },
  stepPill: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 99,
    backgroundColor: Colors.primary,
  },
  stepPillTxt: { fontSize: 12, fontWeight: '700', color: Colors.textInverse },

  // Nav bar
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    gap: 10,
    ...Platform.select({
      ios:     { shadowColor: '#000', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.06, shadowRadius: 6 },
      android: { elevation: 8 },
    }),
  },
  btnBack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 11,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.borderMid,
    backgroundColor: Colors.surface,
    minWidth: 90,
  },
  btnBackArrow: { fontSize: 15, color: Colors.textSub },
  btnBackTxt:   { fontSize: 14, fontWeight: '600', color: Colors.textSub },
  btnNext: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 11,
    paddingHorizontal: 22,
    borderRadius: 8,
    backgroundColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.28,
    shadowRadius: 6,
    elevation: 4,
  },
  btnNextTxt:   { fontSize: 14, fontWeight: '700', color: Colors.textInverse },
  btnNextArrow: { fontSize: 14, color: Colors.textInverse, fontWeight: '700' },
  btnSubmit: {
    paddingVertical: 11,
    paddingHorizontal: 22,
    borderRadius: 8,
    backgroundColor: Colors.success,
    shadowColor: Colors.success,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.28,
    shadowRadius: 6,
    elevation: 4,
  },
  btnDisabled:  { opacity: 0.6 },
  btnSubmitTxt: { fontSize: 14, fontWeight: '700', color: Colors.textInverse },

  // Toast
  toast: {
    position: 'absolute',
    bottom: 90,
    alignSelf: 'center',
    backgroundColor: '#1f2937',
    borderRadius: 99,
    paddingHorizontal: 20,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  toastTxt: { fontSize: 13, fontWeight: '600', color: '#fff' },
});
