import { StyleSheet } from 'react-native';
import { colors } from './shared';

// ─── Request Detail Modal ──────────────────────────────────────────────────────
export const modalStyles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 36,
    paddingTop: 12,
    maxHeight: '85%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: colors.border,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 20,
  },
  modalLoader: { paddingVertical: 48, alignItems: 'center' },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 4 },
  modalRejectBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.red,
    alignItems: 'center',
  },
  modalRejectText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.red,
  },
  modalApproveBtn: {
    flex: 2,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#10b981',
    alignItems: 'center',
  },
  modalApproveText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.white,
  },
  detailSection: { marginBottom: 20 },
  detailSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  detailIcon: { fontSize: 15, marginRight: 8, width: 22 },
  detailValue: {
    fontSize: 15,
    color: colors.textPrimary,
    flex: 1,
  },
  detailEmpty: {
    fontSize: 14,
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  propDetailItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  propDetailIndex: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.blue,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    marginTop: 1,
  },
  propDetailIndexText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
  propDetailInfo: { flex: 1 },
  propDetailAddress: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  propDetailMeta: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  notesBox: {
    backgroundColor: '#fef9c3',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fde047',
  },
  notesText: {
    fontSize: 14,
    color: '#713f12',
    lineHeight: 20,
  },
  requestedOn: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: 20,
  },
});