import { StyleSheet } from 'react-native';

export const C = {
  primary:        '#1A56FF',
  primaryDark:    '#0E3FCC',
  primaryLight:   '#EEF2FF',
  surface:        '#FFFFFF',
  background:     '#F4F6FA',
  border:         '#DDE1EC',
  borderFocus:    '#1A56FF',
  borderError:    '#E53E3E',
  text:           '#111827',
  textSub:        '#6B7280',
  textMuted:      '#9CA3AF',
  textError:      '#E53E3E',
  textOnPrimary:  '#FFFFFF',
  sectionHead:    '#374151',
  divider:        '#F1F5F9',
  successBg:      '#F0FDF4',
  successText:    '#15803D',
  activeBg:       '#EEF2FF',
  activeBorder:   '#1A56FF',
  disabled:       '#93C5FD',
  checkGreen:     '#16A34A',
} as const;

export const SP = { xs: 4, sm: 8, md: 12, base: 16, lg: 20, xl: 24, xxl: 32 } as const;
export const R  = { sm: 6, md: 10, lg: 16, full: 999 } as const;
export const FW = { regular: '400' as const, medium: '500' as const, semi: '600' as const, bold: '700' as const };

export const sharedOfferStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: C.background,
  },
  flex1: { flex: 1 },
  row: { flexDirection: 'row', alignItems: 'center' },
  card: {
    backgroundColor: C.surface,
    borderRadius: R.md,
    padding: SP.base,
    marginBottom: SP.md,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: FW.semi,
    color: C.textSub,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: SP.md,
  },
  searchInput: {
    backgroundColor: C.surface,
    borderRadius: R.md,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: SP.base,
    paddingVertical: SP.md,
    fontSize: 15,
    color: C.text,
    marginBottom: SP.md,
  },
  emptyText: {
    textAlign: 'center',
    color: C.textMuted,
    fontSize: 14,
    marginVertical: SP.xl,
  },
  selectCard: {
    backgroundColor: C.surface,
    borderRadius: R.md,
    borderWidth: 1,
    borderColor: C.border,
    padding: SP.base,
    marginBottom: SP.sm,
  },
  selectCardActive: {
    borderColor: C.activeBorder,
    backgroundColor: C.activeBg,
  },
  selectCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectCardInfo: { flex: 1 },
  selectCardTitle: { fontSize: 15, fontWeight: FW.semi, color: C.text, marginBottom: 2 },
  selectCardSub:   { fontSize: 13, color: C.textSub, marginBottom: SP.xs },
  typeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: C.primaryLight,
    borderRadius: R.full,
    paddingHorizontal: SP.sm,
    paddingVertical: 2,
    marginTop: SP.xs,
  },
  typeBadgeText: { fontSize: 11, color: C.primary, fontWeight: FW.semi },
  checkIcon: { fontSize: 18, color: C.checkGreen, fontWeight: FW.bold },
  inputLabel: {
    fontSize: 13,
    fontWeight: FW.medium,
    color: C.sectionHead,
    marginBottom: SP.xs,
  },
  formInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: R.sm,
    backgroundColor: C.surface,
    paddingHorizontal: SP.md,
    paddingVertical: SP.md,
    fontSize: 15,
    color: C.text,
  },
});
